industries = {
  "advertising": "advertising OR marketing OR \"ad campaign\" OR \"digital ads\" OR \"brand awareness\"",
  "analytics": "analytics OR \"data analysis\" OR \"business intelligence\" OR BI OR \"data insights\"",
  "automotive": "automotive OR cars OR vehicles OR \"electric vehicles\" OR EV OR \"auto industry\"",
  "biotech": "biotech OR biotechnology OR \"genetic engineering\" OR pharma OR \"clinical trials\"",
  "cleantech": "cleantech OR \"clean technology\" OR \"green tech\" OR sustainability OR \"renewable energy\"",
  "consulting": "consulting OR \"business consulting\" OR \"management consulting\" OR advisors OR consultancy",
  "design": "design OR \"graphic design\" OR \"UX/UI\" OR \"product design\" OR \"creative agency\"",
  "ecommerce": "ecommerce OR \"online shopping\" OR \"digital marketplace\" OR \"online retail\"",
  "education": "education OR edtech OR \"online learning\" OR schools OR universities OR \"digital education\"",
  "enterprise": "enterprise OR \"enterprise software\" OR \"B2B tech\" OR \"business solutions\" OR SaaS",
  "fashion": "fashion OR apparel OR clothing OR \"fashion industry\" OR runway OR designers",
  "finance": "finance OR fintech OR \"digital banking\" OR \"financial services\" OR \"investment platform\"",
  "games_video": "gaming OR video games OR esports OR \"game development\" OR \"mobile games\"",
  "government": "government OR policy OR legislation OR \"public sector\" OR politics OR regulation",
  "hardware": "hardware OR devices OR electronics OR \"consumer electronics\" OR gadgets",
  "health": "health OR healthcare OR wellness OR fitness OR \"public health\"",
  "hospitality": "hospitality OR hotels OR resorts OR tourism OR restaurants OR \"guest experience\"",
  "legal": "legal OR law OR \"legal tech\" OR \"court ruling\" OR lawsuits OR attorneys",
  "local": "local news OR \"small business\" OR community OR \"local economy\"",
  "manufacturing": "manufacturing OR factories OR \"industrial production\" OR automation OR industry",
  "medical": "medical OR healthcare OR \"medical research\" OR \"clinical trials\" OR hospitals",
  "messaging": "messaging OR chat OR \"instant messaging\" OR \"communication apps\" OR chatbots",
  "mobile": "mobile OR smartphones OR \"mobile apps\" OR Android OR iOS",
  "music": "music OR artists OR streaming OR concerts OR \"music industry\"",
  "nanotech": "nanotech OR nanotechnology OR \"nano materials\" OR \"nano devices\"",
  "network_hosting": "networking OR hosting OR \"web hosting\" OR \"cloud infrastructure\" OR servers",
  "news": "news OR journalism OR media OR headlines OR \"news coverage\"",
  "nonprofit": "nonprofit OR charity OR NGO OR donations OR \"social impact\"",
  "other": "startups OR tech OR innovation OR emerging OR disruption",
  "pets": "pets OR animals OR \"pet care\" OR \"pet products\" OR \"veterinary care\"",
  "photo_video": "photography OR videography OR \"photo sharing\" OR \"digital media\"",
  "public_relations": "public relations OR PR OR \"media relations\" OR \"press release\"",
  "real_estate": "real estate OR housing OR property OR \"real estate market\" OR \"commercial real estate\"",
  "search": "search OR \"search engine\" OR Google OR Bing OR SEO OR \"web search\"",
  "security": "security OR cybersecurity OR \"data breach\" OR encryption OR \"information security\"",
  "semiconductor": "semiconductor OR chips OR \"chip manufacturing\" OR processors OR Intel OR AMD",
  "social": "social media OR influencers OR \"social networks\" OR Twitter OR Facebook OR Instagram",
  "software": "software OR applications OR platforms OR SaaS OR \"software development\"",
  "sports": "sports OR athletes OR \"sports events\" OR football OR basketball OR Olympics",
  "transportation": "transportation OR logistics OR mobility OR \"public transit\" OR ridesharing",
  "travel": "travel OR tourism OR \"travel industry\" OR flights OR destinations OR airlines",
  "web": "web OR \"web development\" OR \"web apps\" OR websites OR \"internet startups\""
};
